# Generated by Django 6.1.1 on 2026-09-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_keys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='regiao',
        ),
    ]
